CREATE TYPE public.app_role AS ENUM ('admin', 'user');
CREATE TYPE public.lifecycle_status AS ENUM ('supported', 'approaching_eol', 'end_of_life');

CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role public.app_role NOT NULL DEFAULT 'user',
  UNIQUE (user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role)
$$;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;

CREATE POLICY "Users can read own roles" ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Admins manage roles" ON public.user_roles FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE TABLE public.data_sources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  category text NOT NULL,
  description text NOT NULL DEFAULT '',
  source_url text,
  license text,
  last_synced_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.data_sources TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.data_sources TO authenticated;
GRANT ALL ON public.data_sources TO service_role;
ALTER TABLE public.data_sources ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public reads sources" ON public.data_sources FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins manage sources" ON public.data_sources FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  vendor text NOT NULL DEFAULT 'Community',
  category text NOT NULL DEFAULT 'software',
  description text NOT NULL DEFAULT '',
  homepage_url text,
  source_id bigint REFERENCES public.data_sources(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.products TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.products TO authenticated;
GRANT ALL ON public.products TO service_role;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public reads products" ON public.products FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins manage products" ON public.products FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE INDEX products_search_idx ON public.products USING gin (to_tsvector('english', name || ' ' || vendor || ' ' || category || ' ' || description));
CREATE INDEX products_category_idx ON public.products(category);
CREATE INDEX products_vendor_idx ON public.products(vendor);

CREATE TABLE public.release_cycles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  cycle text NOT NULL,
  release_date date,
  support_end date,
  eol_date date,
  latest_version text,
  latest_release_date date,
  status public.lifecycle_status NOT NULL DEFAULT 'supported',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(product_id, cycle)
);
GRANT SELECT ON public.release_cycles TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.release_cycles TO authenticated;
GRANT ALL ON public.release_cycles TO service_role;
ALTER TABLE public.release_cycles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public reads release cycles" ON public.release_cycles FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins manage release cycles" ON public.release_cycles FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE INDEX release_cycles_product_idx ON public.release_cycles(product_id);
CREATE INDEX release_cycles_eol_idx ON public.release_cycles(eol_date);

CREATE TABLE public.provenance_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type text NOT NULL CHECK (entity_type IN ('product','release_cycle','inventory')),
  entity_id bigint NOT NULL,
  source_name text NOT NULL,
  source_url text,
  license text,
  confidence_score numeric(4,3) NOT NULL DEFAULT 1,
  notes text NOT NULL DEFAULT '',
  fetched_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT ON public.provenance_records TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.provenance_records TO authenticated;
GRANT ALL ON public.provenance_records TO service_role;
ALTER TABLE public.provenance_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public reads provenance" ON public.provenance_records FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Admins manage provenance" ON public.provenance_records FOR ALL TO authenticated USING (public.has_role(auth.uid(), 'admin')) WITH CHECK (public.has_role(auth.uid(), 'admin'));
CREATE INDEX provenance_entity_idx ON public.provenance_records(entity_type, entity_id);

CREATE TABLE public.environment_inventories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid NOT NULL,
  environment text NOT NULL,
  product_name text NOT NULL,
  installed_version text NOT NULL,
  business_owner text,
  migration_status text NOT NULL DEFAULT 'Not started',
  eol_date date,
  risk_status public.lifecycle_status NOT NULL DEFAULT 'supported',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.environment_inventories TO authenticated;
GRANT ALL ON public.environment_inventories TO service_role;
ALTER TABLE public.environment_inventories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own inventory" ON public.environment_inventories FOR SELECT TO authenticated USING (owner_id = auth.uid() OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Users insert own inventory" ON public.environment_inventories FOR INSERT TO authenticated WITH CHECK (owner_id = auth.uid() OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Users update own inventory" ON public.environment_inventories FOR UPDATE TO authenticated USING (owner_id = auth.uid() OR public.has_role(auth.uid(), 'admin')) WITH CHECK (owner_id = auth.uid() OR public.has_role(auth.uid(), 'admin'));
CREATE POLICY "Users delete own inventory" ON public.environment_inventories FOR DELETE TO authenticated USING (owner_id = auth.uid() OR public.has_role(auth.uid(), 'admin'));
CREATE INDEX inventory_owner_idx ON public.environment_inventories(owner_id);
CREATE INDEX inventory_risk_idx ON public.environment_inventories(risk_status);
